export const FETCH_POSTS_BEGIN = 'FETCH_POSTS_BEGIN';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_ERROR = 'FETCH_POSTS_ERROR';

export const UPDATE_POST_VOTE_SCORE_BEGIN = 'UPDATE_POST_VOTE_SCORE_BEGIN';
export const UPDATE_POST_VOTE_SCORE_SUCCESS = 'UPDATE_POST_VOTE_SCORE_SUCCESS';
export const UPDATE_POST_VOTE_SCORE_ERROR = 'UPDATE_POST_VOTE_SCORE_ERROR';

export const ADD_POST_BEGIN = 'ADD_POST_BEGIN';
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS';
export const ADD_POST_ERROR = 'ADD_POST_ERROR';

export const DELETE_POST_BEGIN = 'DELETE_POST_BEGIN';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_ERROR = 'DELETE_POST_ERROR';