export const FETCH_POSTS_BEGIN = 'FETCH_POSTS_BEGIN';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_ERROR = 'FETCH_POSTS_ERROR';

export const UPDATE_POST_VOTE_SCORE_BEGIN = 'UPDATE_POST_VOTE_SCORE_BEGIN';
export const UPDATE_POST_VOTE_SCORE_SUCCESS = 'UPDATE_POST_VOTE_SCORE_SUCCESS';
export const UPDATE_POST_VOTE_SCORE_ERROR = 'UPDATE_POST_VOTE_SCORE_ERROR';