export const FETCH_COMMENTS_BEGIN = 'FETCH_COMMENTS_BEGIN';
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
export const FETCH_COMMENTS_ERROR = 'FETCH_COMMENTS_ERROR';

export const UPDATE_COMMENT_VOTE_SCORE_BEGIN = 'UPDATE_COMMENT_VOTE_SCORE_BEGIN';
export const UPDATE_COMMENT_VOTE_SCORE_SUCCESS = 'UPDATE_COMMENT_VOTE_SCORE_SUCCESS';
export const UPDATE_COMMENT_VOTE_SCORE_ERROR = 'UPDATE_COMMENT_VOTE_SCORE_ERROR';

export const POST_COMMENT_BEGIN = 'POST_COMMENT_BEGIN';
export const POST_COMMENT_SUCCESS = 'POST_COMMENT_SUCCESS';
export const POST_COMMENT_ERROR = 'POST_COMMENT_ERROR';

export const EDIT_COMMENT_BEGIN = 'EDIT_COMMENT_BEGIN';
export const EDIT_COMMENT_SUCCESS = 'EDIT_COMMENT_SUCCESS';
export const EDIT_COMMENT_ERROR = 'EDIT_COMMENT_ERROR';

export const DELETE_COMMENT_BEGIN = 'DELETE_COMMENT_BEGIN';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_ERROR = 'DELETE_COMMENT_ERROR';