export const FETCH_COMMENTS_BEGIN = 'FETCH_COMMENTS_BEGIN';
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
export const FETCH_COMMENTS_ERROR = 'FETCH_COMMENTS_ERROR';

export const UPDATE_COMMENT_VOTE_SCORE_BEGIN = 'UPDATE_COMMENT_VOTE_SCORE_BEGIN';
export const UPDATE_COMMENT_VOTE_SCORE_SUCCESS = 'UPDATE_COMMENT_VOTE_SCORE_SUCCESS';
export const UPDATE_COMMENT_VOTE_SCORE_ERROR = 'UPDATE_COMMENT_VOTE_SCORE_ERROR';